<tr>
	<th>{id_label}</th>
	<th>{fleet_label}</th>
	<th>{mission_label}</th>
	<th>{st_owner}</th>
	<th>{st_posit}</th>
	<th>{st_time}</th>
	<th>{en_owner}</th>
	<th>{en_posit}</th>
	<th>{wa_time}</th>
	<th>{en_time}</th>
	<th></th>
</tr>